---
- name: \[linux\] restart node_exporter
  become: true
  systemd:
    daemon_reload: true
    name: node_exporter
    state: restarted
  listen: restart node_exporter
  when: ansible_os_family != 'Darwin'
