---
- name: "[linux] restart node_exporter"
  become: true
  systemd:
    daemon_reload: true
    name: node_exporter
    state: restarted
  listen: restart node_exporter
  when: ansible_os_family != 'Darwin'

- name: "[darwin] restart node_exporter"
  become: true
  shell: launchctl unload /Library/LaunchDaemons/node_exporter.plist; launchctl load /Library/LaunchDaemons/node_exporter.plist
  listen: restart node_exporter
  when: ansible_os_family == 'Darwin'
